/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "palin.h"
#include <string.h>

int *
palin_1_svc(palin_str *argp, struct svc_req *rqstp)
{
	 int  result=0;

        int i,flag=0;
        int len = strlen(argp->str);

        for(i=0;i<len;i++)
        {
        	if(argp->str[i]!=argp->str[len-1])
        	{
        		flag=1;
        		break;
        	}

        }

        if(flag==1)
        {
        	result=0;
        }

        else{
        	result=1;
        }


	return &result;
}
