/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "palin.h"

bool_t
xdr_palin_str (XDR *xdrs, palin_str *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->str, 1000,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
