/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PALIN_H_RPCGEN
#define _PALIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct palin_str {
	char str[1000];
};
typedef struct palin_str palin_str;

#define PALIN_POG 0x12345678
#define PALIN_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define palin 1
extern  int * palin_1(palin_str *, CLIENT *);
extern  int * palin_1_svc(palin_str *, struct svc_req *);
extern int palin_pog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define palin 1
extern  int * palin_1();
extern  int * palin_1_svc();
extern int palin_pog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_palin_str (XDR *, palin_str*);

#else /* K&R C */
extern bool_t xdr_palin_str ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PALIN_H_RPCGEN */
